### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [flyingsonu122/tarana#85] opened 2022-05-17 15:39 UTC
A README is often the first item a visitor will see when visiting your repository. We recommend that your README includes information on:
* What the project does
* Why the project is useful
* How users can get started with the project
* Explain to users that there is a LEARN.md
* Who maintains and contributes to the project

**Comment by SxxAq** [comment] 2022-12-05 15:20
I want to work on this issue please Assign it to me

**Comment by flyingsonu122** [comment] 2022-12-17 11:16
> I want to work on this issue please Assign it to me

@SxxAq pls work on it, consider these points

![image](https://user-images.githubusercontent.com/51280276/208239052-69a14b23-f0a3-421d-9353-319720b9ae63.png)

**Comment by SxxAq** [comment] 2022-12-18 09:15
please Assign to someone else

**Comment by SattyamSamania** [comment] 2022-12-26 14:59
@flyingsonu122 if the issue is still open can I work on this?

**Comment by flyingsonu122** [comment] 2022-12-26 18:39
> @flyingsonu122 if the issue is still open can I work on this?

Yes please

**Comment by flyingsonu122** [comment] 2022-12-26 18:41
> @flyingsonu122 if the issue is still open can I work on this?

Yes please

**Comment by flyingsonu122** [comment] 2022-12-28 13:22
@SattyamSamania any update

**Closed** 2022-12-28 13:25 UTC
Labels: CodePeak 22, points:10
